{% set name = "foundry_ml" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/foundry_ml-{{ version }}.tar.gz
  sha256: 0f6db30dc5b971245591c8465353537442d38f1efefe60951fc65f5ed67e8c3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - openpyxl
    - python >=3.7
    - mdf_forge >=0.8.0
    - globus-sdk >=3,<4
    - dlhub-sdk >=1.0.0
    - numpy >=1.15.4
    - pandas >=0.23.4
    - pydantic >=2.7.2
    - mdf-connect-client >=0.4.0
    - h5py >=2.10.0
    - json2table

test:
  imports:
    - foundry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MLMI2-CSSI/foundry
  summary: Package to support simplified application of machine learning models to datasets in materials science
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
