{% set name = "foundry_ml" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/foundry_ml-{{ version }}.tar.gz
  sha256: 7e0126c85deb6e0ed5e4f92adbc625e35bfdfc24836aa248c04e40a50a078c39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - openpyxl >=3.1.0
    - python >={{ python_min }}
    - mdf_forge >=0.8.0
    - globus-sdk >=3,<4
    - dlhub-sdk >=1.0.0
    - numpy >=1.15.4
    - pandas >=0.23.4
    - pydantic >=2.7.2
    - mdf-connect-client >=0.5.0
    - h5py >=2.10.0
    - json2table

test:
  imports:
    - foundry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MLMI2-CSSI/foundry
  summary: Package to support simplified application of machine learning models to datasets in materials science
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
